/**
 * ForageWise — Sync Queue Module
 *
 * High-level operations for the offline sync queue. Items are queued
 * locally in IndexedDB and processed when the device comes back online.
 *
 * This module is a purely functional data-layer utility — no React hooks
 * or component logic. It wraps the low-level IndexedDB access from db.ts
 * with domain-specific sync queue semantics.
 */

import { getDB } from '@/offline/db';
import type {
  SyncQueueItem,
  SyncQueueStatus,
  SyncOperation,
} from '@/types';

// ---------------------------------------------------------------------------
// Types for enqueue input (fields auto-generated by the module are omitted)
// ---------------------------------------------------------------------------

/** Fields the caller must provide when enqueuing a new sync item. */
export interface EnqueueInput {
  userId: string;
  collection: string;
  operation: SyncOperation;
  payload: unknown;
  serverId?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Generate a SHA-256 hash of the given payload for deduplication.
 *
 * Uses the Web Crypto API (`crypto.subtle`) which is available in modern
 * browsers and service workers. The payload is JSON-serialised before hashing.
 *
 * @param payload - Any JSON-serialisable value.
 * @returns A hex-encoded SHA-256 digest string.
 */
export async function generatePayloadHash(payload: unknown): Promise<string> {
  const text = JSON.stringify(payload);
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

// ---------------------------------------------------------------------------
// Core Queue Operations
// ---------------------------------------------------------------------------

/**
 * Monotonic timestamp counter to ensure unique `createdAt` values even when
 * multiple items are enqueued within the same millisecond. Each call returns
 * a timestamp that is strictly greater than the previous one.
 */
let lastTimestamp = 0;

function getMonotonicTimestamp(): string {
  let now = Date.now();
  if (now <= lastTimestamp) {
    now = lastTimestamp + 1;
  }
  lastTimestamp = now;
  return new Date(now).toISOString();
}

/**
 * Add a new item to the sync queue.
 *
 * Automatically generates:
 * - `localId` via `crypto.randomUUID()`
 * - `createdAt` / `updatedAt` timestamps (ISO 8601, monotonically increasing)
 * - `syncStatus` set to `"pending"`
 * - `retryCount` set to `0`
 * - `clientVersion` set to `1`
 * - `payloadHash` via SHA-256 of the payload
 *
 * @param input - The caller-provided fields for the queue item.
 * @returns The fully-formed {@link SyncQueueItem} that was persisted.
 */
export async function enqueue(input: EnqueueInput): Promise<SyncQueueItem> {
  const db = await getDB();
  const now = getMonotonicTimestamp();
  const payloadHash = await generatePayloadHash(input.payload);

  const item: SyncQueueItem = {
    localId: crypto.randomUUID(),
    serverId: input.serverId,
    userId: input.userId,
    collection: input.collection,
    operation: input.operation,
    payload: input.payload,
    payloadHash,
    createdAt: now,
    updatedAt: now,
    syncStatus: 'pending',
    retryCount: 0,
    clientVersion: 1,
  };

  await db.put('syncQueue', item);
  return item;
}

/**
 * Get the next pending item from the queue (oldest first by `createdAt`).
 *
 * Uses the `by-createdAt` index so items are naturally ordered by timestamp,
 * with ties broken by primary key (`localId`) in ascending order. This
 * guarantees a deterministic FIFO order even when items share the same
 * `createdAt` value.
 *
 * @returns The oldest pending {@link SyncQueueItem}, or `undefined` if the
 *          queue has no pending items.
 */
export async function dequeue(): Promise<SyncQueueItem | undefined> {
  const db = await getDB();
  const tx = db.transaction('syncQueue', 'readonly');
  const index = tx.store.index('by-createdAt');

  let cursor = await index.openCursor();
  while (cursor) {
    const item = cursor.value;
    if (item.syncStatus === 'pending') {
      await tx.done;
      return item;
    }
    cursor = await cursor.continue();
  }

  await tx.done;
  return undefined;
}

/**
 * Mark a queue item as in-progress.
 *
 * @param localId - The local identifier of the queue item.
 */
export async function markInProgress(localId: string): Promise<void> {
  await updateStatus(localId, 'in-progress');
}

/**
 * Mark a queue item as done (successfully synced).
 *
 * Optionally associates the server-generated ID with the item.
 *
 * @param localId  - The local identifier of the queue item.
 * @param serverId - Optional server-side ID to store on the item.
 */
export async function markDone(
  localId: string,
  serverId?: string,
): Promise<void> {
  const db = await getDB();
  const item = await db.get('syncQueue', localId);
  if (!item) return;

  item.syncStatus = 'done';
  item.updatedAt = new Date().toISOString();
  if (serverId !== undefined) {
    item.serverId = serverId;
  }
  await db.put('syncQueue', item);
}

/**
 * Mark a queue item as failed and increment its retry count.
 *
 * @param localId - The local identifier of the queue item.
 */
export async function markFailed(localId: string): Promise<void> {
  const db = await getDB();
  const item = await db.get('syncQueue', localId);
  if (!item) return;

  item.syncStatus = 'failed';
  item.retryCount += 1;
  item.updatedAt = new Date().toISOString();
  await db.put('syncQueue', item);
}

// ---------------------------------------------------------------------------
// Query Helpers
// ---------------------------------------------------------------------------

/**
 * Get all items with a `"pending"` sync status.
 *
 * @returns An array of pending {@link SyncQueueItem}s.
 */
export async function getPending(): Promise<SyncQueueItem[]> {
  return getByStatus('pending');
}

/**
 * Get all items with a `"failed"` sync status.
 *
 * @returns An array of failed {@link SyncQueueItem}s.
 */
export async function getFailed(): Promise<SyncQueueItem[]> {
  return getByStatus('failed');
}

/**
 * Get all items targeting a specific collection.
 *
 * @param collection - The collection name to filter by (e.g. `"trips"`).
 * @returns An array of {@link SyncQueueItem}s for that collection.
 */
export async function getByCollection(
  collection: string,
): Promise<SyncQueueItem[]> {
  const db = await getDB();
  return db.getAllFromIndex('syncQueue', 'by-collection', collection);
}

// ---------------------------------------------------------------------------
// Maintenance
// ---------------------------------------------------------------------------

/**
 * Remove all items with a `"done"` sync status from the queue.
 *
 * This is a housekeeping operation to keep the IndexedDB store lean.
 */
export async function clearDone(): Promise<void> {
  const db = await getDB();
  const tx = db.transaction('syncQueue', 'readwrite');
  const index = tx.store.index('by-syncStatus');

  let cursor = await index.openCursor(IDBKeyRange.only('done'));
  while (cursor) {
    await cursor.delete();
    cursor = await cursor.continue();
  }

  await tx.done;
}

/**
 * Reset failed items back to `"pending"` so they can be retried.
 *
 * Items whose `retryCount` has reached or exceeded `maxRetries` are left
 * in the `"failed"` state.
 *
 * @param maxRetries - Maximum number of retries allowed. Defaults to `3`.
 * @returns The number of items that were reset to pending.
 */
export async function retryFailed(maxRetries: number = 3): Promise<number> {
  const db = await getDB();
  const tx = db.transaction('syncQueue', 'readwrite');
  const index = tx.store.index('by-syncStatus');
  let resetCount = 0;

  let cursor = await index.openCursor(IDBKeyRange.only('failed'));
  while (cursor) {
    const item = cursor.value;
    if (item.retryCount < maxRetries) {
      item.syncStatus = 'pending';
      item.updatedAt = new Date().toISOString();
      await cursor.update(item);
      resetCount += 1;
    }
    cursor = await cursor.continue();
  }

  await tx.done;
  return resetCount;
}

// ---------------------------------------------------------------------------
// Internal Utilities
// ---------------------------------------------------------------------------

/**
 * Retrieve all queue items matching a given sync status.
 *
 * @param status - The {@link SyncQueueStatus} to filter by.
 * @returns An array of matching {@link SyncQueueItem}s.
 */
async function getByStatus(status: SyncQueueStatus): Promise<SyncQueueItem[]> {
  const db = await getDB();
  return db.getAllFromIndex('syncQueue', 'by-syncStatus', status);
}

/**
 * Update the sync status of a queue item and refresh its `updatedAt` timestamp.
 *
 * @param localId - The local identifier of the queue item.
 * @param status  - The new {@link SyncQueueStatus}.
 */
async function updateStatus(
  localId: string,
  status: SyncQueueStatus,
): Promise<void> {
  const db = await getDB();
  const item = await db.get('syncQueue', localId);
  if (!item) return;

  item.syncStatus = status;
  item.updatedAt = new Date().toISOString();
  await db.put('syncQueue', item);
}
